version: '3.8'
services: 
    flaskr:
        image: sea_battle_server:latest
        build: 
            context: ./back
        environment: 
            FLASK_APP: flaskr/__init__.py
        ports: 
            - 5000:5000
        restart: always
        depends_on: 
            - postgres
        command: python manage.py run -h 0.0.0.0

    postgres:
        image: postgres:12-alpine
        restart: always
        environment:
            POSTGRES_DB: sea_battle
            POSTGRES_HOST_AUTH_METHOD: trust
            POSTGRES_PASSWORD: ""
            POSTGRES_USER: postgres
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
        ports: 
            - 5432:5432
volumes:
    postgres_data:
        


 
